project_id = "kyysnciirgauhzzqobly"

[functions.agent-chat]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.agent-runtime]
verify_jwt = false

[functions.create-agent]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.assign-admin-role]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
